version: "3.9"
services:
  mongo:
    restart: always
    image: mongo
    volumes: 
    - db_data:/data/db
  dart:
    restart: always
    build: .
    depends_on:
    - mongo
    volumes: 
    - packages:/packages
    entrypoint: ["/app/bin/server.exe"]
    ports: 
    - 8080:8080
volumes: 
  packages:
  db_data:

