version: "3.9"
services:
  mongo:
    restart: always
    image: mongo
    volumes: 
    - db_data:/data/db
  dart:
    restart: always
    build: .
    depends_on:
    - mongo
    volumes: 
    - packages:/packages
    entrypoint: ["/app/bin/server.exe"]
    
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
      - dart
    ports:
      - 80:80
      - 443:443
    volumes: 
      - caddy_data:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
volumes: 
  packages:
  db_data:
  caddy_data:

